spring:
  redis:
    database: 1
    pool: 6379
    host: localhost
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

rocketmq:
  name-server: 127.0.0.1:9876

